language: java

matrix:
  include:
    - os: linux
      arch: arm64
      jdk: openjdk11
    - os: linux
      arch: s390x
      jdk: openjdk11
      addons:
        apt:
          update: true
          packages:
            - maven
            - libcppunit-dev

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev

install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
     sudo apt-get install maven;
    fi
  mvn -version

script:
  - mvn -B -V -e clean
  - mvn clean -B -V -e
  - mvn verify
  - mvn -DskipTests spotbugs:check checkstyle:check -Pfull-build
  - mvn clean verify -B -V -e -DskipTests spotbugs:check checkstyle:check -Pfull-build

branches:
  only:
  - master
  - branch-3.7
  - branch-3.6
  - branch-3.5
