language: java

matrix:
  include:
    - os: linux
      arch: arm64
      jdk: openjdk11
    - os: linux
      arch: s390x
      jdk: openjdk11
      addons:
        apt:
          update: true
          packages:
            - maven
            - libcppunit-dev

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev

install:
  - curl -o apache.tar.gz "https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz"
  - tar -xzf apache.tar.gz
  # make alias of mvn to realpath of mvn
  - alias workingmvn=$PWD/apache-maven-3.9.9/bin/mvn
  - workingmvn -version

script:
  - workingmvn clean verify-DskipTests spotbugs:check checkstyle:check -Pfull-build

branches:
  only:
  - master
  - branch-3.7
  - branch-3.6
  - branch-3.5
