language: java

matrix:
  include:
    - os: linux
      arch: arm64
      jdk: openjdk11
    - os: linux
      arch: s390x
      jdk: openjdk11
      addons:
        apt:
          update: true
          packages:
            - maven
            - libcppunit-dev

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev

before_install:
  - curl -o apache.tar.gz "https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz"
  - tar -xzf apache.tar.gz
  - alias mvn="./apache-maven-3.9.9/bin/mvn"

install:
  - mvn -version

script:
  - mvn -B -V -e clean
  - mvn clean -B -V -e
  - mvn verify
  - mvn -DskipTests spotbugs:check checkstyle:check -Pfull-build
  - mvn clean verify -B -V -e -DskipTests spotbugs:check checkstyle:check -Pfull-build

branches:
  only:
  - master
  - branch-3.7
  - branch-3.6
  - branch-3.5
